# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://sarunast.com
paginate:         1
baseurl:          /
author:
  name:           Sarunas Tamasauskas
  url:            http://sarunast.com
  email:          sarunas.tamasauskas@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
